USE adventures_in_the_jungle;

CREATE TABLE CHOICE
(
    CHOICE_ID   INT PRIMARY KEY NOT NULL,
    CHOICE_NAME VARCHAR(50)     NOT NULL
);

CREATE TABLE ITEM
(
    ITEM_ID   INT PRIMARY KEY NOT NULL,
    ITEM_NAME VARCHAR(50)     NOT NULL
);

CREATE TABLE ATTRIBUTE
(
    ATTRIBUTE_ID   INT PRIMARY KEY NOT NULL,
    ATTRIBUTE_NAME VARCHAR(50)     NOT NULL
);

CREATE TABLE ITEM_CHOICE
(
    ITEM_ID   INT NOT NULL REFERENCES ITEM (ITEM_ID),
    CHOICE_ID INT NOT NULL REFERENCES CHOICE (CHOICE_ID),
    PRIMARY KEY (ITEM_ID, CHOICE_ID)
);

CREATE TABLE ITEM_ATTRIBUTE
(
    ITEM_ID      INT NOT NULL REFERENCES ITEM (ITEM_ID),
    ATTRIBUTE_ID INT NOT NULL REFERENCES ATTRIBUTE (ATTRIBUTE_ID),
    PRIMARY KEY (ITEM_ID, ATTRIBUTE_ID)
);
