CREATE TABLE SCENARIO
(
    SCENARIO_ID   INT PRIMARY KEY NOT NULL,
    SCENARIO_TEXT NVARCHAR        NOT NULL
);

CREATE TABLE CHOICE
(
    CHOICE_ID       INT PRIMARY KEY NOT NULL,
    CHOICE_TEXT     NVARCHAR        NOT NULL,
    CHOICE_LEADS_TO INT REFERENCES SCENARIO (SCENARIO_ID)
);

CREATE TABLE SCENARIO_CHOICE
(
    SCENARIO_ID INT REFERENCES SCENARIO (SCENARIO_ID) NOT NULL,
    CHOICE_ID   INT REFERENCES CHOICE (CHOICE_ID)     NOT NULL,
    PRIMARY KEY (SCENARIO_ID, CHOICE_ID)
);
